apiVersion: v2
name: cluster-vsphere
version: 4.1.2
home: https://github.com/giantswarm/cluster-vsphere
icon: https://s.giantswarm.io/app-icons/vsphere/2/icon-light.png
sources:
  - https://github.com/giantswarm/cluster-vsphere
description: "A helm chart for creating Cluster API clusters with the vSphere provider (CAPV)."
keywords:
  - capv
  - vsphere
  - vmware
annotations:
  application.giantswarm.io/team: rocket
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
restrictions:
  compatibleProviders:
    - vsphere
dependencies:
  - name: cluster
    version: "5.1.1-04d0d8d9e8088758bb8ea24a9bbee87272c0cda7"
    repository: "https://giantswarm.github.io/cluster-test-catalog"
  - name: cluster-shared
    version: "0.7.1"
    repository: "https://giantswarm.github.io/cluster-catalog"
