{{/* vSphere-specific network-policies Helm values*/}}
{{/* https://github.com/giantswarm/network-policies-app/blob/main/helm/network-policies-app/values.yaml */}}
{{- define "vSphereNetworkPoliciesHelmValues" }}
allowEgressToDNS:
  enabled: true
{{- if eq $.Values.cluster.providerIntegration.resourcesApi.controlPlaneResource.provider "kamaji" }}
kamaji: 
  enabled: true
{{- end }}
{{- end }}
