{{- if (include "isKamaji" $) }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-kamaji-etcd
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
    helm.sh/resource-policy: keep  # Remove when tenantcontrolplane no longer depends on it
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    giantswarm.io/service-priority: "{{ .Values.global.metadata.servicePriority }}"
    {{- include "labels.common" . | nindent 4 }}
spec:
  suspend: false
  releaseName: {{ include "resource.default.name" $ }}-kamaji-etcd
  targetNamespace: {{ $.Release.Namespace }}
  storageNamespace: {{ $.Release.Namespace }}
  chart:
    spec:
      chart: kamaji-etcd 
      {{- $_ := set $ "appName" "kamaji-etcd" }}
      version: {{ include "cluster.app.version" $ }}
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-{{ include "cluster.app.catalog" $ }}
  interval: 5m
  install:
    remediation:
      retries: -1
  serviceAccountName: automation
  upgrade:
    remediation:
      retries: -1
  values:
    datastore:
      name: {{ include "resource.default.name" $ }}
{{- end }}
