{{- if (include "isKamaji" $) }}
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  labels:
    app.kubernetes.io/managed-by: kyverno-policy-operator
  name: {{ include "resource.default.name" $ }}-kamaji-tenantcontrolplane
  namespace: policy-exceptions
spec:
  background: true
  exceptions:
  - policyName: disallow-capabilities-strict
    ruleNames:
    - autogen-require-drop-all
    - require-drop-all
  - policyName: disallow-privilege-escalation
    ruleNames:
    - autogen-privilege-escalation
    - privilege-escalation
  - policyName: require-run-as-nonroot
    ruleNames:
    - autogen-run-as-non-root
    - run-as-non-root
  - policyName: restrict-seccomp-strict
    ruleNames:
    - autogen-check-seccomp-strict
    - check-seccomp-strict
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - Pod
        - ReplicaSet
        selector:
          matchLabels:
            kamaji.clastix.io/name: {{ include "resource.default.name" $ }}
        namespaces:
        - {{ $.Release.Namespace }}
{{- end }}
